图片镜像插件 - 大升级
School-Robot/Python-Plugins pull request #18
Opened 2024-08-22 09:22 UTC by cnrenil

2024-08-22 09:35 UTC, Plutossnow requested changes

2024-08-22 09:35 UTC, Plutossnow commented on sdust_emojiZ_mirror_picture.py
> +                if key in raw_message:
这里建议严格判断触发词 使用==不要用in

2024-08-22 09:35 UTC, Plutossnow commented on sdust_emojiZ_mirror_picture.py
>                          self.log.error(f"下载失败，状态码: {response.status_code}")
这里没return

2024-08-22 10:20 UTC, cnrenil commented on sdust_emojiZ_mirror_picture.py
> +                if key in raw_message:
不好处理，需要先把cq码去掉

2024-08-22 10:40 UTC, cnrenil commented
不要合并，bug很多

2024-08-23 13:44 UTC, closed without merging

2024-08-23 13:44 UTC, cnrenil commented
此版本需要进一步调试和优化，关闭合并