今天吃什么分校区版
School-Robot/Python-Plugins pull request #35
Opened 2024-12-08 08:36 UTC by qiuyuyang910

2024-12-08 09:44 UTC, f00001111 requested changes

2024-12-08 09:44 UTC, f00001111 commented on README.md
> +{"msg":[{"foodName":string,"storeName":string,"location":string,"campus":麦庐/枫林/蛟桥,"takeout":bool},],"total":int}
加个带说明的例子

2024-12-08 09:44 UTC, f00001111 commented on jxufe_qiuyuyang_eatWhat.py
> +                ret_msg = "秋雨样awa\n\n吃什么:三校区随机\n在麦庐/枫林/蛟桥吃什么:线下该校区随机\n在麦庐/枫林/蛟桥吃什么外卖:外卖该校区随机"
校区可以不在这写

2024-12-08 13:36 UTC, qiuyuyang910 commented on jxufe_qiuyuyang_eatWhat.py
> +                ret_msg = "秋雨样awa\n\n吃什么:三校区随机\n在麦庐/枫林/蛟桥吃什么:线下该校区随机\n在麦庐/枫林/蛟桥吃什么外卖:外卖该校区随机"
是不要写具体校区么？

2024-12-08 16:55 UTC, f00001111 commented on jxufe_qiuyuyang_eatWhat.py
> +                ret_msg = "秋雨样awa\n\n吃什么:三校区随机\n在麦庐/枫林/蛟桥吃什么:线下该校区随机\n在麦庐/枫林/蛟桥吃什么外卖:外卖该校区随机"
是的，可以直接去掉或者从配置文件里读取，代码理论上在加载器是不能做修改的

2024-12-10 01:09 UTC, f00001111 approved these changes

2024-12-10 01:10 UTC, merged