search_music_X1a0Yu
School-Robot/Python-Plugins pull request #4
Opened 2024-08-03 13:59 UTC by X1a0-Yu

实现Bot使用音频发送指定音乐
例如：音乐-See You Again

2024-08-03 14:10 UTC, f00001111 requested changes
将插件ID中的`.`替换为`_`后作为文件名

2024-08-03 14:10 UTC, f00001111 commented on search_music_X1a0Yu.py
> +plugin_id = "X1a0Yu_tiangou_word"
使用规范ID，例如：`xxx.yyy.zzz`

2024-08-03 14:10 UTC, f00001111 commented on search_music_X1a0Yu.py
> +                    data = response.get('data', {})
使用`code`判断后不需要重复判断，`dict`中使用`['key']`即可取值，如需判断是否为空应使用`in`进行判断

2024-08-03 14:10 UTC, f00001111 commented on search_music_X1a0Yu.py
> +                        src = data.get('src')
同上

2024-08-03 14:10 UTC, f00001111 commented on search_music_X1a0Yu.py
> +                            need_send_message += self.util.cq_reply(message_id)
语音消息应单独发送，不应和其他消息相连，如需发送混合消息请分条发送

2024-08-03 14:10 UTC, f00001111 commented on search_music_X1a0Yu.py
> +                            need_send_message = "[CQ:record,file={}]".format(src)
使用`util`中`cq_record`转换为CQ码，例如`need_send_message = self.util.cq_record(url)`

2024-08-03 14:10 UTC, f00001111 commented on search_music_X1a0Yu.py
> +                print(f"Request failed: {e}")
使用注册时传入的`log`进行日志记录，不要出现`print`等输出函数

2024-08-03 14:10 UTC, f00001111 commented on search_music_X1a0Yu.py
> +                print(f"Failed to parse JSON: {e}")
同上

2024-08-03 14:10 UTC, f00001111 commented on search_music_X1a0Yu.py
> +                print(f"Missing key in response: {e}")
同上

2024-08-03 14:10 UTC, f00001111 commented on search_music_X1a0Yu.py
> +            res = raw_message.replace('音乐-', '', 1)
`res`是否需要进行URL编码

2024-08-03 14:10 UTC, f00001111 commented on search_music_X1a0Yu.py
> +from urllib.parse import quote
是否为无效引用

2024-08-03 14:37 UTC, Plutossnow commented on X1a0Yu_search_music.py
> +                print(f"Request failed: {e}")
日志记录请使用self.log.info()

2024-08-03 14:37 UTC, Plutossnow commented on X1a0Yu_search_music.py
> +                print(f"Failed to parse JSON: {e}")
同上

2024-08-03 14:37 UTC, Plutossnow commented on X1a0Yu_search_music.py
> +API_PRE_FIX = "http://api.caonmtx.cn/api/wangyi.php?msg="
全局变量建议置于文件开头

2024-08-05 05:51 UTC, closed without merging

2024-08-05 05:51 UTC, f00001111 commented
能用了再开吧